engines:
  eslint:
    enabled: true
  stylelint:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
        typescript:
          mass_threshold: 70

ratings:
   paths:
    - "**.ts"
    - "**.tsx"
    - "**.css"

exclude_paths:
- static/**/*
