import React from 'react'
import Helmet from 'react-helmet'
import { graphql } from 'gatsby'
import Layout from 'src/components/layout'
import PostList from 'src/components/PostList'

import {
	AuthorPageQuery,
	PostListFieldsFragment
} from 'autogenerated/graphql-types'

const Author: React.FC<{ data: AuthorPageQuery }> = ({ data }) => {
	const posts = data.wpUser?.posts?.nodes
	const name = data.wpUser?.name
	const totalCount = (posts && posts.length) || 0
	const title = `${totalCount} post${totalCount === 1 ? '' : 's'} by ${name}`

	return (
		<Layout>
			<Helmet title={`${name}`} />
			<PostList posts={posts ?? []} title={title} />
		</Layout>
	)
}

export default Author

export const pageQuery = graphql`
	query AuthorPage($id: String!) {
		wpUser(id: { eq: $id }) {
			name
			posts {
				nodes {
					...PostListFields
				}
			}
		}
	}
`
