import React from 'react'
import { graphql } from 'gatsby'
import Layout from 'src/components/layout'

import { PageByIdQuery } from 'autogenerated/graphql-types'
import { Helmet } from 'react-helmet'
import { BreadcrumbsFactory } from 'src/components/layout/breadcrumbs'
import RecommendedPosts from 'src/components/post/recommended-posts/RecommendedPosts'

type TemplateProps = {
  title: string
  content: string
}

export const PageTemplate: React.FC<TemplateProps> = ({ title, content }) => {
  return (
    <div className="container content">
      <div className="columns">
        <div className="column is-three-quarters">
          <h1 className="is-size-2 has-text-weight-bold is-bold-light">
            {title}
          </h1>
          <div dangerouslySetInnerHTML={{ __html: content }} />
        </div>
        <div className="column">
          <RecommendedPosts />
        </div>
      </div>
    </div>
  )
}

type Props = {
  data: PageByIdQuery
}

const Page: React.FC<Props> = ({ data }) => {
  const { wpPage: page } = data

  return (
    <Layout
      title={page?.title}
      breadcrumbs={[BreadcrumbsFactory.currentPage(page?.title || '')]}
    >
      <PageTemplate title={page?.title ?? ''} content={page?.content ?? ''} />
    </Layout>
  )
}

export default Page

export const pageQuery = graphql`
  query PageById($id: String!) {
    wpPage(id: { eq: $id }) {
      title
      content
    }
  }
`
