import React from 'react'
import { WpBlock } from 'autogenerated/graphql-types'
import Infocard from '../infocard/Infocard'
import './infocard.scss'

export type Props = {
	blocks: (WpBlock | null)[] | null
}

export const InfocardList: React.FC<Props> = ({ blocks }) => {
	if (blocks === null) return null
	return (
		<div className="columns has-text-centered is-multiline infocard-list">
			{blocks?.map((block, i) => {
				if (block === null) return null
				const {} = block

				return (
					<div className="column is-half" key={i}>
						<Infocard
							title={attrs?.title ?? ''}
							text={attrs?.text ?? ''}
							img={JSON.parse(decodeURI(attrs?.image ?? ''))['url']}
							infoUrl={attrs?.url ?? ''}
						/>
					</div>
				)
			})}
		</div>
	)
}

export default InfocardList
