import React from 'react'
import { graphql, useStaticQuery } from 'gatsby'
import { parseISO } from 'date-fns'

import Card from './Card'

import { RecommendedPostsQuery } from 'autogenerated/graphql-types'

import './recommended-posts.scss'

const query = graphql`
	query RecommendedPosts {
		allWpPost(limit: 3, sort: { order: DESC, fields: date }) {
			edges {
				node {
					title
					slug
					date
					post_preview {
						previewImage {
							sourceUrl
							altText
						}
					}
				}
			}
		}
	}
`

export type Props = {}

export const RecommendedPosts: React.FC<Props> = ({}) => {
	const data = useStaticQuery<RecommendedPostsQuery>(query)
	const { edges } = data.allWpPost

	return (
		<div className="recommended-posts">
			<div className="box has-text-centered header">
				<h4>Ieteiktie raksti</h4>
			</div>
			<div className="posts">
				{edges.map(({ node }, i) => (
					<div className="box" key={i}>
						<Card
							title={node.title ?? ''}
							image={{
								url: node.post_preview?.previewImage?.sourceUrl ?? '',
								alt: node.post_preview?.previewImage?.altText ?? ''
							}}
							path={node.slug ?? ''}
							date={parseISO(node.date) ?? new Date()}
						/>
					</div>
				))}
			</div>
		</div>
	)
}

export default RecommendedPosts
