import { WpBlock, Maybe } from 'autogenerated/graphql-types'

type BlockLike = {
    name: string
}

const getWpBlockByName = <T extends BlockLike>(name: string, blocks: (T | null)[] | null) => {
    if (blocks === null) return null

    const block = blocks.find(x => x?.name === name)
    return block === undefined
        ? null
        : block
}

const getWpBlocksByName = <T extends BlockLike>(name: string, blocks: (T | null)[] | null) => {
    if (blocks === null) return null

    return blocks.filter(x => x?.name === name)

}

export { getWpBlockByName, getWpBlocksByName }

