import { WpBlock, Maybe } from 'autogenerated/graphql-types'

const getWpBlockByName = (name: string, blocks: (WpBlock | null)[] | null) => {
    if (blocks === null) return null

    const block = blocks.find(x => x?.name === name)
    return block === undefined
        ? null
        : block
}

const getWpBlocksByName = (name: string, blocks: (WpBlock | null)[] | null) => {
    if (blocks === null) return null

    return blocks.filter(x => x?.name === name)

}

export { getWpBlockByName, getWpBlocksByName }

