import React, { useState } from 'react'
import { useStaticQuery, graphql } from 'gatsby'

import FullCalendar from '@fullcalendar/react'
import dayGridPlugin from '@fullcalendar/daygrid'
import momentPlugin from '@fullcalendar/moment'
import interactionPlugin from '@fullcalendar/interaction'
import { VerboseFormattingArg, View } from '@fullcalendar/core'

import { isSameDay, format, parseISO, parse } from 'date-fns'

import './calendar.scss'
import Events, { CalendarEventType } from './Events'
import { EventsQuery } from 'autogenerated/graphql-types'

const query = graphql`
  query Events {
    allWpEvent {
      nodes {
        title
        event {
          date
          link {
            url
            title
            target
          }
        }
      }
    }
  }
`

export type Props = {}

const dateNames = ['Sv', 'P', 'O', 'T', 'C', 'Pk', 'S']
const formatColumnsHeader = (options: VerboseFormattingArg) => {
  const date = new Date(options.date.year, options.date.month, options.date.day)
  return dateNames[date.getDay()]
}

const formatTitle = (options: VerboseFormattingArg) => {
  const date = new Date(options.date.year, options.date.month, options.date.day)
  const monthName = date.toLocaleString('lv-LV', { month: 'long' })
  const capitalizedMonthName =
    monthName[0].toLocaleUpperCase() + monthName.slice(1)
  return `${capitalizedMonthName} ${options.date.year}`
}

type DayRenderArg = {
  view: View
  date: Date
  allDay?: boolean
  el: HTMLElement
}

const renderDay = (events: CalendarEventType[]) => (arg: DayRenderArg) => {
  const dayEvents = events.filter(x => isSameDay(arg.date, x.date))

  if (dayEvents.length === 0) return

  const dayElement = document.querySelector(
    `.fc-day-top[data-date="${format(arg.date, 'yyyy-MM-dd')}"]`
  )

  if (dayElement === null) return

  dayElement.classList.add('has-event')
}

export const Calendar: React.FC<Props> = () => {
  const data = useStaticQuery<EventsQuery>(query)
  const { nodes } = data.allWpEvent

  const events: CalendarEventType[] = nodes.map(({ title, event }) => ({
    title: title ?? '',
    date: parse(event?.date, 'dd/MM/yyyy', new Date())
  }))

  const [selectedDay, selectDay] = useState<Date | null>(null)

  return (
    <>
      <FullCalendar
        defaultView="dayGridMonth"
        plugins={[dayGridPlugin, momentPlugin, interactionPlugin]}
        themeSystem="standart"
        height="auto"
        header={{
          left: 'prev',
          center: 'title',
          right: 'next'
        }}
        firstDay={1}
        titleFormat={formatTitle}
        columnHeaderFormat={formatColumnsHeader}
        eventRender={_ => false}
        dayRender={renderDay(events)}
        dateClick={event => selectDay(event.date)}
      />
      <Events events={events} selectedDate={selectedDay} />
    </>
  )
}

export default Calendar
